version: 2

# This configuration is used ONLY for creating the GitHub release from pre-built artifacts.
# It skips the build process entirely and expects archives to already exist in the release/ directory.

dist: release

# Skip all builds - we're only creating a release from existing artifacts
builds:
  - skip: true

# Archive configuration - must match the naming from other configs
archives:
  - id: mcp-k6-archives
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "mcp-k6_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CLAUDE.md

# Checksum configuration
checksum:
  name_template: "mcp-k6_{{ .Version }}_checksums.txt"
  algorithm: sha256

# GitHub release configuration
release:
  github:
    owner: grafana
    name: mcp-k6

  # Draft release (set to false for automatic publishing)
  draft: true

  # Prerelease detection
  prerelease: auto

  # Release name
  name_template: "v{{ .Version }}"

  # Release footer with installation instructions
  footer: |
    ## Installation

    ### Quick Install (Unix-like systems)

    ```bash
    # Download and extract (replace {OS} and {ARCH} with your platform)
    curl -L https://github.com/grafana/mcp-k6/releases/download/v{{ .Version }}/mcp-k6_{{ .Version }}_{OS}_{ARCH}.tar.gz | tar xz

    # Move to PATH
    sudo mv mcp-k6 /usr/local/bin/

    # Verify installation
    mcp-k6 --version
    ```

    ### Supported Platforms

    - **macOS**: darwin_amd64, darwin_arm64
    - **Linux**: linux_amd64, linux_arm64
    - **Windows**: windows_amd64

    ### Checksums

    SHA256 checksums are available in `mcp-k6_{{ .Version }}_checksums.txt`

# Snapshot configuration
snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
